---
title: "TBB"
author: "Sebastian Zeki"
date: "22/04/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(here)
library(EndoMineR)

```


### Import the data
```{r dataImport,echo=FALSE}
load(file=here("data", "TheOGDReportFinal.rda"))
load(file=here("data", "PathDataFrameFinal.rda"))

head(Myendo)
```

### Pre-process both the pathology and the endoscopy text:
```{r echo=FALSE}
read_chunk(here("inst","TemplateProject","munge", "B_DataClean.R"))
```

```{r dataClean,echo=FALSE}
```

### Merge endoscopy and pathology text
```{r echo=FALSE}
read_chunk(here("inst","TemplateProject","munge", "C_DataMerge.R"))
```

```{r dataMerge,echo=FALSE}
```

### Clean the endoscopist and instrument columns
```{r echo=FALSE}
read_chunk(here("inst","TemplateProject","munge", "D_DataClean2.R"))
```

```{r dataClean2,echo=FALSE}
```

### Extract number of biopsies, biopsy size, biopsy location and medications from the text
```{r echo=FALSE}
read_chunk(here("inst","TemplateProject","munge", "E_DataExtrapolate.R"))
```

```{r dataExtrapolate,echo=FALSE}

```

### Extract endoscopy events
```{r echo=FALSE}
read_chunk(here("inst","TemplateProject","munge", "F_DataExtrapolate2.R"))
```

```{r dataExtrapolate2,echo=FALSE}

```

### Extract some generic analyses
```{r echo=FALSE}
read_chunk(here("inst","TemplateProject","munge", "G_Analysis_Generic.R"))
```

```{r dataGeneric,echo=FALSE}

```

### Extract some disease specific analyses
```{r echo=FALSE}
read_chunk(here("inst","TemplateProject","munge", "G_Analysis_Generic.R"))
```

```{r dataGeneric,echo=FALSE}

```